using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rock_Paper_Scissors_Lizard_Spock
{
    class Computer : Player
    {
        
        //member variables (Has A)


        public override void chooseGesture()
        {

        }
        public override void chooseName()
        {

        }
        //Random need to look up MSDN - Random
        // Constructor






        // member methods
    }
}
